const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const RunbookAI = sequelize.define(
  'RunbookAI',
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    db_type: {
      type: DataTypes.ENUM('mysql', 'redis', 'postgresql', 'mongodb', 'oracle', 'db2', 'edb', 'sqlserver', 'other'),
      allowNull: false,
      comment: 'Type of database (sqlserver for MS SQL/MSSQL)',
    },
    title: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    tutorial: {
      type: DataTypes.TEXT('long'),
      allowNull: true,
      comment: 'Full tutorial / documentation content (Markdown supported)',
    },
    summary: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    rank: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Display order / priority rank',
    },
    tags: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Array of tag strings',
    },
    author_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    flag: {
      type: DataTypes.SMALLINT,
      defaultValue: 1,
      comment: '1=published, 0=draft/deleted',
    },
    version: {
      type: DataTypes.STRING(50),
      allowNull: true,
      comment: 'Database version (e.g., MySQL 8.0.36, PostgreSQL 16.2)',
    },
    version_history: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Array of version history objects with date and changes',
    },
    ai_generated: {
      type: DataTypes.SMALLINT,
      defaultValue: 0,
      comment: '1=generated by AI, 0=manual entry',
    },
    ai_source: {
      type: DataTypes.STRING(100),
      allowNull: true,
      comment: 'AI model used (e.g., opencode/big-pickle, GPT-4)',
    },
    last_ai_update: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'Last time AI updated this entry',
    },
    auto_update: {
      type: DataTypes.SMALLINT,
      defaultValue: 1,
      comment: '1=auto update enabled, 0=disabled',
    },
  },
  {
    tableName: 'dokumentasi_db',
  }
);

module.exports = RunbookAI;
