const { RunbookAI } = require('../models/index');
const { logActivity } = require('../middleware/activityLogger');
const logger = require('../utils/logger');
const { websearch, webfetch } = require('./aiTools');

const DB_TYPES = [
  { type: 'mysql', name: 'MySQL', currentVersion: '8.0.36' },
  { type: 'postgresql', name: 'PostgreSQL', currentVersion: '16.2' },
  { type: 'redis', name: 'Redis', currentVersion: '7.2.4' },
  { type: 'mongodb', name: 'MongoDB', currentVersion: '7.0.6' },
  { type: 'oracle', name: 'Oracle Database', currentVersion: '21c' },
  { type: 'sqlserver', name: 'MS SQL Server', currentVersion: '2022' },
  { type: 'edb', name: 'EnterpriseDB (EDB)', currentVersion: '16.2' },
  { type: 'db2', name: 'IBM DB2', currentVersion: '11.5' },
  { type: 'banking', name: 'Banking Systems', currentVersion: '2026' },
];

const AI_MODEL = 'opencode/big-pickle';

const getLatestVersion = async (dbType) => {
  try {
    const searchQuery = `${dbType} latest version 2026`;
    const results = await websearch({ query: searchQuery, count: 3 });

    if (results && results.length > 0) {
      const versionRegex = /(\d+\.\d+(\.\d+)?|(\d{4}))/g;
      const matches = results[0].title?.match(versionRegex) ||
        results[0].snippet?.match(versionRegex);
      if (matches && matches.length > 0) {
        return matches[0];
      }
    }
    return null;
  } catch (err) {
    logger.error(`Error fetching version for ${dbType}:`, err.message);
    return null;
  }
};

const generateTutorial = async (dbType, dbName, version) => {
  try {
    const searchQuery = `${dbName} ${version} tutorial administration management guide`;
    const results = await websearch({ query: searchQuery, count: 5, type: 'deep' });

    let content = `# ${dbName} ${version} - Database Management Tutorial\n\n`;
    content += `> Last updated: ${new Date().toISOString().split('T')[0]} | AI Generated\n\n`;

    if (results && results.length > 0) {
      content += `## Overview\n\n`;
      results.slice(0, 3).forEach((r, i) => {
        content += `### ${r.title || `Source ${i + 1}`}\n`;
        content += `${r.snippet || 'No description available'}\n\n`;
        if (r.url) content += `Source: ${r.url}\n\n`;
      });
    }

    content += `## Installation & Setup\n\n`;
    content += `Please refer to official documentation for ${dbName} installation.\n\n`;
    content += `## Common Operations\n\n`;
    content += `- Backup and Recovery\n`;
    content += `- Performance Tuning\n`;
    content += `- User Management\n`;
    content += `- Monitoring\n\n`;

    return content;
  } catch (err) {
    logger.error(`Error generating tutorial for ${dbType}:`, err.message);
    return `# ${dbName} ${version}\n\nTutorial content temporarily unavailable.`;
  }
};

const updateAllDatabases = async (req = null) => {
  const results = { updated: 0, skipped: 0, errors: [] };

  for (const db of DB_TYPES) {
    try {
      const latestVersion = await getLatestVersion(db.type);
      const versionToUse = latestVersion || db.currentVersion;

      let doc = await RunbookAI.findOne({
        where: { db_type: db.type, flag: 1 },
        order: [['createdAt', 'DESC']]
      });

      if (doc) {
        if (doc.auto_update === 0) {
          results.skipped++;
          continue;
        }

        if (doc.version !== versionToUse) {
          const tutorial = await generateTutorial(db.type, db.name, versionToUse);

          const versionHistory = doc.version_history || [];
          versionHistory.push({
            version: versionToUse,
            date: new Date().toISOString(),
            changes: `Updated to version ${versionToUse} by AI`
          });

          await doc.update({
            version: versionToUse,
            tutorial,
            summary: `${db.name} ${versionToUse} database management tutorial - Auto-updated by AI`,
            version_history: versionHistory.slice(-10),
            ai_generated: 1,
            ai_source: AI_MODEL,
            last_ai_update: new Date(),
          });

          results.updated++;

          if (req && req.user) {
            await logActivity(req, 'UPDATE', 'dokumentasi',
              `AI auto-updated: ${db.name} to v${versionToUse}`);
          }
        } else {
          results.skipped++;
        }
      } else {
        const tutorial = await generateTutorial(db.type, db.name, versionToUse);

        await RunbookAI.create({
          db_type: db.type,
          title: `${db.name} ${versionToUse} Management Tutorial`,
          tutorial,
          summary: `${db.name} ${versionToUse} database management tutorial - Generated by AI`,
          version: versionToUse,
          version_history: [{
            version: versionToUse,
            date: new Date().toISOString(),
            changes: `Initial creation by AI`
          }],
          ai_generated: 1,
          ai_source: AI_MODEL,
          last_ai_update: new Date(),
          auto_update: 1,
          rank: 0,
          tags: [db.type, 'tutorial', 'ai-generated'],
          flag: 1,
        });

        results.updated++;
      }

      await new Promise(resolve => setTimeout(resolve, 1000));

    } catch (err) {
      logger.error(`Error updating ${db.type}:`, err.message);
      results.errors.push({ db: db.type, error: err.message });
    }
  }

  return results;
};

const updateSingleDatabase = async (dbType, req = null) => {
  const dbInfo = DB_TYPES.find(d => d.type === dbType);
  if (!dbInfo) throw new Error(`Unknown database type: ${dbType}`);

  const latestVersion = await getLatestVersion(dbType);
  const versionToUse = latestVersion || dbInfo.currentVersion;
  const tutorial = await generateTutorial(dbType, dbInfo.name, versionToUse);

  let doc = await RunbookAI.findOne({
    where: { db_type: dbType, flag: 1 },
    order: [['createdAt', 'DESC']]
  });

  if (doc) {
    const versionHistory = doc.version_history || [];
    versionHistory.push({
      version: versionToUse,
      date: new Date().toISOString(),
      changes: `Manual AI update to version ${versionToUse}`
    });

    await doc.update({
      version: versionToUse,
      tutorial,
      version_history: versionHistory.slice(-10),
      last_ai_update: new Date(),
      ai_source: AI_MODEL,
    });
  } else {
    doc = await RunbookAI.create({
      db_type: dbType,
      title: `${dbInfo.name} ${versionToUse} Management Tutorial`,
      tutorial,
      summary: `${dbInfo.name} ${versionToUse} database management tutorial`,
      version: versionToUse,
      version_history: [{
        version: versionToUse,
        date: new Date().toISOString(),
        changes: 'Created by AI'
      }],
      ai_generated: 1,
      ai_source: AI_MODEL,
      last_ai_update: new Date(),
      auto_update: 1,
      rank: 0,
      tags: [dbType, 'tutorial', 'ai-generated'],
      flag: 1,
    });
  }

  return doc;
};

const aiGenerateNewDoc = async (dbType, title, req = null) => {
  const latestVersion = await getLatestVersion(dbType) || 'Latest';
  const tutorial = await generateTutorial(dbType, title, latestVersion);

  const doc = await RunbookAI.create({
    db_type: dbType,
    title: title,
    tutorial,
    summary: `${title} documentation - Generated by AI`,
    version: latestVersion,
    version_history: [{
      version: latestVersion,
      date: new Date().toISOString(),
      changes: 'Initial creation by AI'
    }],
    ai_generated: 1,
    ai_source: AI_MODEL,
    last_ai_update: new Date(),
    auto_update: 1,
    rank: 0,
    tags: [dbType, 'tutorial', 'ai-generated'],
    flag: 1,
  });

  return doc;
};

module.exports = {
  updateAllDatabases,
  updateSingleDatabase,
  getLatestVersion,
  generateTutorial,
  aiGenerateNewDoc,
  DB_TYPES,
};
